substitutions:
  devicename: nmbm8036
  upper_devicename: "NnBm8036 Controler"
  low_devicename: nmbm8036

external_components:
  - source:
      type: git
      url: https://github.com/Brokly/ESPHome-NM8036-BM8036-/my_components/nmbm8036/
    components: [ nmbm8036 ]
    refresh: 0s

esphome:
  name: $devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  manual_ip:
    static_ip: !secret ip_nmbm8036
    gateway: !secret gateway 
    subnet: !secret subnet
    dns1: !secret dns1
    dns2: !secret dns2
  ap:
    ssid:  ${upper_devicename} Hotspot
    password: !secret ap_wifi_pass

logger:
    level: DEBUG
    baud_rate: 0
    
api:

ota:
  password: !secret ota_pass

captive_portal:
    
web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_pass

#последовательный порт ВНИМАНИЕ СПЕЦИФИЧЕСКАЯ НАСТРОЙКА
uart:
  id: uart_bus
  tx_pin: GPIO14
  rx_pin: GPIO27
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 2 
  
#версия прошивки
text_sensor:
  - platform: version
    name: $upper_devicename ESPHome Version

sensor:
  #датчик отображающий уровень сигнала Wifi
  - platform: wifi_signal
    name: $upper_devicename Signal
    update_interval: 60s
  #bm8036 имеет на борту RTC, можно использовать как источник точного времени
  - platform: "nmbm8036"
    name: $upper_devicename
    id: nmbm8036_id
    # не забываем подключить uart
    uart_id: uart_bus
    # минимальный диапазон публикации сенсоров лучше не делать меньше 5 сек
    update_interval: 20s
    # нога на которой висит диод активности обмена с bm8036, если нужен визуальный контроль обмена данными
    pin: 
       number: GPIO16
    # температурных сенсоров может быть 32
    temperature_0:
       name: ${upper_devicename} Termo 0
       id: t0_id
    temperature_1:
       name: ${upper_devicename} Termo 1
       id: t1_id
    temperature_2:
       name: ${upper_devicename} Termo 2
       id: t2_id
    temperature_3:
       name: ${upper_devicename} Termo 3
       id: t3_id
    temperature_4:
       name: ${upper_devicename} Termo 4
       id: t4_id
    temperature_5:
       name: ${upper_devicename} Termo 5
       id: t5_id
    temperature_6:
       name: ${upper_devicename} Termo 6
       id: t6_id
    temperature_7:
       name: ${upper_devicename} Termo 7
       id: t7_id
    temperature_8:
       name: ${upper_devicename} Termo 8
       id: t8_id
    temperature_9:
       name: ${upper_devicename} Termo 9
       id: t9_id
    temperature_10:
       name: ${upper_devicename} Termo 10
       id: t10_id
    temperature_11:
       name: ${upper_devicename} Termo 11
       id: t11_id
    temperature_12:
       name: ${upper_devicename} Termo 12
       id: t12_id
    temperature_13:
       name: ${upper_devicename} Termo 13
       id: t13_id
    temperature_14:
       name: ${upper_devicename} Termo 14
       id: t14_id
    temperature_15:
       name: ${upper_devicename} Termo 15
       id: t15_id
    temperature_16:
       name: ${upper_devicename} Termo 16
       id: t16_id
    temperature_17:
       name: ${upper_devicename} Termo 17
       id: t17_id
    temperature_18:
       name: ${upper_devicename} Termo 18
       id: t18_id
    temperature_19:
       name: ${upper_devicename} Termo 19
       id: t19_id
    temperature_20:
       name: ${upper_devicename} Termo 20
       id: t20_id
    temperature_21:
       name: ${upper_devicename} Termo 21
       id: t21_id
    temperature_22:
       name: ${upper_devicename} Termo 22
       id: t22_id
    temperature_23:
       name: ${upper_devicename} Termo 23
       id: t23_id
    temperature_24:
       name: ${upper_devicename} Termo 24
       id: t24_id
    temperature_25:
       name: ${upper_devicename} Termo 25
       id: t25_id
    temperature_26:
       name: ${upper_devicename} Termo 26
       id: t26_id
    temperature_27:
       name: ${upper_devicename} Termo 27
       id: t27_id
    temperature_28:
       name: ${upper_devicename} Termo 28
       id: t28_id
    temperature_29:
       name: ${upper_devicename} Termo 29
       id: t29_id
    temperature_30:
       name: ${upper_devicename} Termo 30
       id: t30_id
    temperature_31:
       name: ${upper_devicename} Termo 31
       id: t31_id
       
    # серийные номера температурных сенсоров, может быть 32
    ds_address_0:
       name: ${upper_devicename} Dallss SN 0
       id: sn0_id
    ds_address_1:
       name: ${upper_devicename} Dallss SN 1
       id: sn1_id
    ds_address_2:
       name: ${upper_devicename} Dallss SN 2
       id: sn2_id
    ds_address_3:
       name: ${upper_devicename} Dallss SN 3
       id: sn3_id
    ds_address_4:
       name: ${upper_devicename} Dallss SN 4
       id: sn4_id
    ds_address_5:
       name: ${upper_devicename} Dallss SN 5
       id: sn5_id
    ds_address_6:
       name: ${upper_devicename} Dallss SN 6
       id: sn6_id
    ds_address_7:
       name: ${upper_devicename} Dallss SN 7
       id: sn7_id
    ds_address_8:
       name: ${upper_devicename} Dallss SN 8
       id: sn8_id
    ds_address_9:
       name: ${upper_devicename} Dallss SN 9
       id: sn9_id
    ds_address_10:
       name: ${upper_devicename} Dallss SN 10
       id: sn10_id
    ds_address_11:
       name: ${upper_devicename} Dallss SN 11
       id: sn11_id
    ds_address_12:
       name: ${upper_devicename} Dallss SN 12
       id: sn12_id
    ds_address_13:
       name: ${upper_devicename} Dallss SN 13
       id: sn13_id
    ds_address_14:
       name: ${upper_devicename} Dallss SN 14
       id: sn4_id
    ds_address_15:
       name: ${upper_devicename} Dallss SN 15
       id: sn15_id
    ds_address_16:
       name: ${upper_devicename} Dallss SN 16
       id: sn16_id
    ds_address_17:
       name: ${upper_devicename} Dallss SN 17
       id: sn17_id
    ds_address_18:
       name: ${upper_devicename} Dallss SN 18
       id: sn18_id
    ds_address_19:
       name: ${upper_devicename} Dallss SN 19
       id: sn19_id
    ds_address_0:
       name: ${upper_devicename} Dallss SN 20
       id: sn20_id
    ds_address_1:
       name: ${upper_devicename} Dallss SN 21
       id: sn21_id
    ds_address_22:
       name: ${upper_devicename} Dallss SN 22
       id: sn22_id
    ds_address_23:
       name: ${upper_devicename} Dallss SN 23
       id: sn23_id
    ds_address_24:
       name: ${upper_devicename} Dallss SN 24
       id: sn24_id
    ds_address_25:
       name: ${upper_devicename} Dallss SN 25
       id: sn25_id
    ds_address_26:
       name: ${upper_devicename} Dallss SN 26
       id: sn26_id
    ds_address_27:
       name: ${upper_devicename} Dallss SN 27
       id: sn27_id
    ds_address_28:
       name: ${upper_devicename} Dallss SN 28
       id: sn28_id
    ds_address_29:
       name: ${upper_devicename} Dallss SN 29
       id: sn29_id
    ds_address_30:
       name: ${upper_devicename} Dallss SN 30
       id: sn30_id
    ds_address_31:
       name: ${upper_devicename} Dallss SN 31
       id: sn31_id

    # внешних выходов - 12
    output_0:
       name: ${upper_devicename} Output 0
       id: out0_id
    output_1:
       name: ${upper_devicename} Output 1
       id: out1_id
    output_2:
       name: ${upper_devicename} Output 2
       id: out2_id
    output_3:
       name: ${upper_devicename} Output 3
       id: out3_id
    output_4:
       name: ${upper_devicename} Output 4
       id: out4_id
    output_5:
       name: ${upper_devicename} Output 5
       id: out5_id
    output_6:
       name: ${upper_devicename} Output 6
       id: out6_id
    output_7:
       name: ${upper_devicename} Output 7
       id: out7_id
    output_8:
       name: ${upper_devicename} Output 8
       id: out8_id
    output_9:
       name: ${upper_devicename} Output 9
       id: out9_id
    output_10:
       name: ${upper_devicename} Output 10
       id: out10_id
    output_11:
       name: ${upper_devicename} Output 11
       id: out11_id
    # АЦП 4 канала
    input_0:
       name: ${upper_devicename} In ADC 0
       id: in0_id
    input_1:
       name: ${upper_devicename} In ADC 1
       id: in1_id
    # напряжение батарейки RTC
    rtc_battery_voltage:
       name: ${upper_devicename} RTC Battery Voltage
       id: batt_id
    # статус связи с bm8036
    connect_status:
       name: ${upper_devicename} Uart Link Status
       id: err_id
    # версия прошивки bm8036
    firmware_version:
       name: ${upper_devicename} Firmware Version
       id: firm_id
    
time:
  # синхронизация времени на NM8036
  - platform: sntp
    id: cycle
    on_time:
      # Every 5 minutes
     - seconds: 0
       minutes: /15
       then:
         nmbm8036.write_time:
            id: nmbm8036_id